//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetskiySad.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public int IdKids { get; set; }
        public int IdTeacher { get; set; }
    
        public virtual Kids Kids { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
